### PR TITLE
Match files ending with `Dockerfile`

### PR DESCRIPTION
**Pull request by russellcardullo**
Some projects name their Dockerfiles like `name.Dockerfile`.

This change edits the glob to also match those files when running the
action.

### CODE REVIEW

**Comment by mgrachev** [comment]
@russellcardullo 👋 Thank you for your contribution! 👍

I see some warnings from the shellcheck linter. Can you take a look at them?

**Comment by russellcardullo** [comment]
@mgrachev Sure can.  I update the PR with shellcheck issues fixed.

**Review by mgrachev — APPROVED** [review]

**Comment by review-dog** [comment]
Hi, @russellcardullo! We merged your PR to reviewdog! 🐶
Thank you for your contribution! ✨

**We just invited you to join the @reviewdog organization on GitHub.**
Accept the invite by visiting https://github.com/orgs/reviewdog/invitation.
By joining the team, you'll be a part of reviewdog community and can help the maintainance of reviewdog.

Thanks again!

**Comment by mgrachev** [comment]
@russellcardullo Thank you 🙂

**Pull request merged**
